Rename some cops to follow up of Rubocop v0.68
If it ran with Rubocop v0.68, it causes error with following message.

```

$ bundle exec rubocop
Error: The `Layout/FirstParameterIndentation` cop has been renamed to `Layout/IndentFirstArgument`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/meowcop-1.18.0/config/rubocop.yml, please update it)
The `Layout/IndentArray` cop has been renamed to `Layout/IndentFirstArrayElement`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/meowcop-1.18.0/config/rubocop.yml, please update it)
The `Layout/IndentHash` cop has been renamed to `Layout/IndentFirstHashElement`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/meowcop-1.18.0/config/rubocop.yml, please update it)
```

This patch will fix the errors.